Mysite2/Mysite2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('News.urls')),
    path('',include('isi.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Mysite2/News/urls.py
from django.urls import path
from. import views

app_name = 'News'

urlpatterns = [
    path('trending/',views.trending, name ='trending'),
    path('Lifestyle/',views.Lifestyle, name ='Lifestyle'),
    path('Sports/',views.Sports, name ='Sports'),
    path('Entertainment/',views.Entertainment, name ='Entertainment'),
    path('Politik/',views.Politik, name ='Politik'),
    path('Healty/',views.Healty, name ='Healty'),
    path('all/',views.all, name ='all'),
    path('isi/<int:id>',views.isi, name ='isi'),
]

Mysite2/isi/urls.py
from django.urls import path
from. import views

app_name = 'isi'

urlpatterns = [
    path('berita/',views.isi,name ='berita.html')
]

Mysite2/News/models.py
from django.db import models
from Mysite2 import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

# Create your models here.

class CustomuserManager(BaseUserManager):
    def _create_user(self, email, name ,  phone , is_admin, is_staff, is_active, status, password, **extra_fields):
        if not email :
            raise ValueError("The Given username must be set")

        email = self.normalize_email(email)
        user = self.model(email = email , name = name, phone = phone, is_admin = is_admin, is_staff = is_staff, is_active = is_active, status = status, password = password, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)


        return user

    def create_user(self, email, name, phone , is_admin, is_staff, is_active, status, password=None, **extra_fields):
        return self._create_user(email, name, phone, is_admin, is_staff, True, status, password, **extra_fields)


    def create_superuser(self, email, name, phone, is_admin, is_staff, is_active, status, password = None, **extra_fields):
        return self._create_user(email, name , phone, True, True, True, status=='admin', password, **extra_fields, is_superuser = True)


class Customuser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255 , unique=True)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, blank=True, null=True)
    is_admin = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    status_list = [
        ('admin','admin'),
        ('viewers','viewers')
    ]
    password = models.CharField(max_length=255)
    status = models.CharField(max_length=255, choices=status_list, blank=True,null=True, default='admin')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'password', 'phone','status','is_admin', 'is_staff', 'is_active']
    object


    objects = CustomuserManager()


    def __str__(self):
        return '{}|{}'.format(self.name,self.email)

class kategori (models.Model):
    namakategori = models.CharField(max_length=255)

    def __str__(self):
        return self.namakategori
        


class berita(models.Model):
    STATUS = ('publish', 'publish'),('draft', 'draft')

    judul = models.CharField(max_length=255)
    isi = models.CharField(max_length=9999)
    kategori = models.ForeignKey(kategori,on_delete=models.CASCADE)
    kategoriID = models.IntegerField()
    gambar = models.ImageField(upload_to='media', height_field=None, width_field=None, max_length=100)
    penulis = models.CharField(max_length=255)
    fotopenulis = models.ImageField(upload_to='media', height_field=None, width_field=None, max_length=100, null=True)
    status = models.CharField(choices=STATUS, max_length=200)
    publikasi = models.CharField(max_length=255)    
    deskripsi = models.CharField(max_length=255)

Mysite2/News/views.py
from django.shortcuts import render, get_object_or_404
from. import models
# Create your views here.

def all(request):
    if 'cari' in request.GET:
        cari = request.GET['cari']
        berita = models.berita.objects.filter(judul__icontains=cari)
    else :
        berita = models.berita.objects.all()
    
    context = {'beritas' : berita}
    return render(request, 'menu/all.html', context)

def isi (request, id):
    berita = get_object_or_404(models.berita, pk=id)
    context = {'beritas' : berita}
    return render(request, 'menu/berita.html', context)


def trending (request):
   
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 19
    if catID : 
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')

    context = {'beritas' : berita, 'kategori' : kategori}

    return render(request, 'menu/trending.html', context)

def Politik (request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 20
    if catID : 
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')

    context = {'beritas' : berita, 'kategori' : kategori}

    return render(request, 'menu/Politik.html', context)

def Sports (request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 21
    if catID : 
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')

    context = {'beritas' : berita, 'kategori' : kategori}
    return render(request, 'menu/Sports.html', context)

def Lifestyle (request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 4
    if catID : 
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')

    context = {'beritas' : berita, 'kategori' : kategori}
    return render(request, 'menu/Lifestyle.html', context)

def Entertainment (request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 23
    if catID : 
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')

    context = {'beritas' : berita, 'kategori' : kategori}
    return render(request, 'menu/Entertainment.html', context)

def Healty (request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 6
    if catID : 
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')

    context = {'beritas' : berita, 'kategori' : kategori}
    return render(request, 'menu/Healty.html', context)

Mysite2/News/templates/menu/Healty.html
{% extends 'core/base.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>
                        {% block title %}{% endblock %}
                    </title>
                    {% block htmlhead %}
                    {% load static %}
                    <link rel="stylesheet" type="text/css" href="{% static 'trending.css' %}">
                    {% endblock htmlhead %}
                    </head>
                    <body>
                        {% block content %} 
                    <center><h3>INFORMATION </h3> </center>



                    </div>
                        
                      <br>
                      <br>
                      <br>
                      <!-- Card -->

                      <div class="container text-center">
                        <div class="row">
                          <div class="col">
                            <div class="card" style="width: 18rem;">
                                <img src="https://www.filmify.in/wp-content/uploads/2022/08/My-project-1-2022-08-13T162408.629.jpg" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                </div>
                              </div>
                          </div>
                          <div class="col">
                            <div class="card" style="width: 18rem;">
                                <img src="https://static-koimoi.akamaized.net/wp-content/new-galleries/2020/01/tanhaji-the-unsung-warriors-day-1-vs-top-10-openers-of-ajay-devgn-where-will-it-stand-001.jpg" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                </div>
                              </div>
                          </div>
                          <div class="col">
                            <div class="card" style="width: 18rem;">
                                <img src="https://www.koimoi.com/wp-content/new-galleries/2020/01/tanhaji-box-office-ajay-devgn-starrer-vs-war-kabir-singh-recent-250-cr-grossers-will-it-be-able-to-touch-the-mark-001.jpg" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>





                      <!-- Card Long -->
                      <br>
                      <br>
                      

                     <center><h3>TOP MOVIE</h3></center> 
                     <br>
                     <br>
                      <div class="container text-center">
                        <div class="row">
                          <div class="col">
                            <img src="https://roost.nbcuni.com/bin/viewasset.html/content/dam/Peacock/Landing-Pages/campaign/fnaf/fnaf-trailer-thumbnail.jpg/_jcr_content/renditions/original.JPG" class="card-img-top" style="filter: brightness ;">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
                          </div>
                          <div class="col">
                            <img src="https://studio.mrngroup.co/storage/app/media/Prambors/Editorial/TOP%20GUN%20MAVERICK-20220628083958.png?tr=w-600" class="card-img-top" alt="...">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
                          </div>
                          <div class="col">
                                <img src="https://imgx.sonora.id/crop/0x0:0x0/x/photo/2023/10/18/killersaffichejpg-20231018011020.jpg" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <h5 class="card-title">Card title</h5>
                                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                  <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>

                      <div class="container text-center">
                        <div class="row">
                          <div class="col">
                            <div class="container text-center">
                              <h1 style="text-align: left; margin: bottom 30px;">{{beritas.judulLengkap}}</h1>
                                <div class="row">
                                    {% for berita in beritas %}
                                  <div class="col">
                                    <div class="card" style="width: 18rem;">
                                        <img src="{{berita.gambar.url}}" class="card-img-top" >
                                        <div class="card-body"> {{berita.kategori}}
                                          <h5 class="card-title">{{berita.judul}}</h5>
                                          <p class="card-text">{{berita.deskripsi}}</p>
                                          <a href="{% url 'News:isi' berita.id %}" class="btn btn-primary btn-danger">click here</a>
                                        </div>
                                      </div>
                                  </div>
                                  {% endfor %}
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>
                       <!-- Site footer -->

                       <footer class="site-footer">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-12 col-md-6">
                                    <h6>About</h6>
                                    <p class="text-justify">Scanfcode.com
                                        <i>CODE WANTS TO BE SIMPLE
                                        </i>
                                        is an initiative to help the upcoming programmers with the code. Scanfcode
                                        focuses on providing the most efficient code or snippets as the code wants to be
                                        simple. We will help programmers build up concepts in different programming
                                        languages that include C, C++, Java, HTML, CSS, Bootstrap, JavaScript, PHP,
                                        Android, SQL and Algorithm.</p>
                                </div>

                                <div class="col-xs-6 col-md-3">
                                    <h6>Categories</h6>
                                    <ul class="footer-links">
                                        <li>
                                            <a href="http://scanfcode.com/category/c-language/">C</a>
                                        </li>
                                        <li>
                                            <a href="http://scanfcode.com/category/front-end-development/">UI Design</a>
                                        </li>
                                        <li>
                                            <a href="http://scanfcode.com/category/back-end-development/">PHP</a>
                                        </li>
                                        <li>
                                            <a href="http://scanfcode.com/category/java-programming-language/">Java</a>
                                        </li>
                                        <li>
                                            <a href="http://scanfcode.com/category/android/">Android</a>
                                        </li>
                                        <li>
                                            <a href="http://scanfcode.com/category/templates/">Templates</a>
                                        </li>
                                    </ul>
                                </div>

                                <div class="col-xs-6 col-md-3">
                                    <h6>Quick Links</h6>
                                    <ul class="footer-links">
                                        <li>
                                            <a href="http://scanfcode.com/about/">About Us</a>
                                        </li>
                                        <li>
                                            <a href="http://scanfcode.com/contact/">Contact Us</a>
                                        </li>
                                        <li>
                                            <a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a>
                                        </li>
                                        <li>
                                            <a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a>
                                        </li>
                                        <li>
                                            <a href="http://scanfcode.com/sitemap/">Sitemap</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <hr></div>
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-8 col-sm-6 col-xs-12">
                                        <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by
                                            <a href="#">Scanfcode</a>.
                                        </p>
                                    </div>

                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        <ul class="social-icons">
                                            <li>
                                                <a class="facebook" href="#">
                                                    <i class="fa fa-facebook"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="twitter" href="#">
                                                    <i class="fa fa-twitter"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="dribbble" href="#">
                                                    <i class="fa fa-dribbble"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="linkedin" href="#">
                                                    <i class="fa fa-linkedin"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        
                        </footer>
                        {% endblock content %}
                    
                            
                    </body>

Mysite2/News/templates/menu/all.html
{% extends 'core/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 
        {% block title %}{% endblock %}
    </title>
    {% block htmlhead %}
    {% load static %}

    {% endblock htmlhead %}
</head>
<body>
    {% block content %}
<!-- HTML CODE HERE -->

<!-- Slide -->
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://st.depositphotos.com/1011646/1255/i/450/depositphotos_12553000-stock-photo-breaking-news-screen.jpg" class="d-block w-100" height="600">
      </div>
      <div class="carousel-item">
        <img src="https://cdn0-production-images-kly.akamaized.net/S-RhXhu70IkhiK1eIqxXTCfDHPo=/800x450/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4158836/original/096116200_1663215998-rm389-a10-google-mockup.jpg" class="d-block w-100" height="600">
      </div>
      <div class="carousel-item">
        <img src="https://ichef.bbci.co.uk/news/640/cpsprodpb/1654A/production/_131666419_banner_4_1920_.png" class="d-block w-100" height="600">
      </div>
    </div>
  </div>

    <br>
    <br>
  <!-- Card -->

<center><p>BERITA TERKINI</p></center>
  <br>
  <div class="container text-center">
    <div class="row">
      <div class="col">
        <div class="container text-center">
          <h1 style="text-align: left; margin: bottom 30px;">{{beritas.judulLengkap}}</h1>
            <div class="row">
                {% for berita in beritas %}
              <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="{{berita.gambar.url}}" class="card-img-top" >
                    <div class="card-body"> {{berita.kategori}}
                      <h5 class="card-title">{{berita.judul}}</h5>
                      <p class="card-text">{{berita.deskripsi}}</p>
                      <a href="{% url 'News:isi' berita.id %}" class="btn btn-primary btn-danger">click here</a>
                    </div>
                  </div>
              </div>
              {% endfor %}
            </div>
          </div>
      </div>
    </div>
  </div>

   








    {% endblock %}
</body>
</html>